name: Deploy to Edgeone

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@6e295a6a0c9087bf374299e9d67f9d2edab9f18f # v3.0.0
        with:
          hugo-version: '0.128.2'
          extended: true

      - name: Build
        run: |
          rm -rf public
          hugo --minify --baseURL "/"

      - name: Deploy to EdgeOne Pages
        run: npx edgeone@1.6.28 pages deploy ./public --name 5b2-site --token ${{ secrets.EDGEONE_API_TOKEN }}
